- lib/rambling/trie/stringifyable.rb
Hello. 
In ruby 2.7.1 (latest stable for now) `#to_s` method for some singleton object (e.g. `nil`, `false`, `true`) returns frozen string.  `<<` modifies the receiver string and can't be used for frozen objects, so `nil.to_s << "hello" will throw an error. I replaced `<<` concatenation with simple `+`.
> Frozen string issue fix.

- spec/support/shared_examples/a_serializer.rb
So that tests in semaphore don't fail because of a small byte difference in compression depending on ruby version.
> Be more lax with file size

- spec/lib/rambling/trie/container_spec.rb
To actually test the non-matching tree shared example for compressed tries.
> Add missing `compress!` in container spec

- .coveralls.yml
- .semaphore/semaphore.yml
- README.md
* Update `.coveralls.yml` to point to `semaphore`
* On `.semaphore/semaphore.yml`:
* Rename pipeline to `Run specs in all supported rubies'
* Extract `checkout` command to `global_job_config.prologue`
* Add `3.2.2`, `3.1.4`, `3.0.6`, `2.7.8` tasks
* Correctly configure main `3.2.2` task to publish test report, now being picked up by Semaphore 
* Remove unnecessary formatters from non-`3.2.2` tasks
* On badges:
* Change `README.md` to have one badge per line instead of all in one giant line
* Add RubyGems downloads badge
* Add CodeClimate issues badge
* Update docs badge to point directly to [rubydoc.info/gems/rambling-trie](http://rubydoc.info/gems/rambling-trie)
* Update license badge to one from shields.io
> Update badges, CI and coveralls reporting

- .gitignore
- lib/rambling/trie/serializers/zip.rb
- spec/support/shared_examples/a_serializer.rb
- Add test in `a serializer` shared examples
- Implement method for `Rambling::Trie::Serializers::Zip`
> Ensure all serializer #dump methods return the size of the file

- lib/rambling/trie/enumerable.rb
- lib/rambling/trie/readers/plain_text.rb
- spec/lib/rambling/trie/enumerable_spec.rb
- spec/lib/rambling/trie/readers/plain_text_spec.rb
… depending on whether a block is given or not.
> Ensure `#each`/`#each_word` return `Enumerator`/`self`

- lib/rambling/trie.rb
- lib/rambling/trie/comparable.rb
- lib/rambling/trie/compressible.rb
- lib/rambling/trie/configuration/properties.rb
- lib/rambling/trie/configuration/provider_collection.rb
- lib/rambling/trie/container.rb
- lib/rambling/trie/enumerable.rb
- lib/rambling/trie/nodes/compressed.rb
- lib/rambling/trie/nodes/node.rb
- lib/rambling/trie/nodes/raw.rb
- lib/rambling/trie/readers.rb
- lib/rambling/trie/readers/plain_text.rb
- lib/rambling/trie/readers/reader.rb
- lib/rambling/trie/serializers.rb
- lib/rambling/trie/serializers/file.rb
- lib/rambling/trie/serializers/marshal.rb
- lib/rambling/trie/serializers/serializer.rb
- lib/rambling/trie/serializers/yaml.rb
- lib/rambling/trie/serializers/zip.rb
- lib/rambling/trie/stringifyable.rb
- spec/lib/rambling/trie/readers/reader_spec.rb
- spec/lib/rambling/trie/serializers/serializer_spec.rb
- Add `Readers::Reader` and `Serializer::Serializer` base classes 
- Make all readers/serializers extend from their corresponding base classes
- Better docs with `Reader`/`Serializer` and generics
- Fix all code blocks from `\`` to `+` and add some more
- Add `@return [void]` where appropriate
- Add `@return [self]` where appropriate
- Fix `Nodes::Node` duplicate and broken references
- Fix some typos and add some missing periods
> Improve API documentation

- lib/rambling/trie.rb
- rambling-trie.gemspec
- spec/support/shared_examples/a_trie_node.rb
And add explicit RubyMine `noinspection` comments for things that RuboCop already takes care of.
> Code inspections in `lib/` - use `%w` and `https` in gemspec

- spec/integration/rambling/trie_spec.rb
- spec/lib/rambling/trie/configuration/provider_collection_spec.rb
- spec/lib/rambling/trie/container_spec.rb
- spec/lib/rambling/trie/nodes/compressed_spec.rb
- spec/lib/rambling/trie/nodes/raw_spec.rb
- spec/lib/rambling/trie/serializers/file_spec.rb
- spec/lib/rambling/trie/serializers/marshal_spec.rb
- spec/lib/rambling/trie/serializers/yaml_spec.rb
- spec/lib/rambling/trie/serializers/zip_spec.rb
- spec/lib/rambling/trie_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples/a_container_word.rb
- spec/support/shared_examples/a_serializable_trie.rb
- spec/support/shared_examples/a_serializer.rb
- spec/support/shared_examples/a_trie_node.rb
... instead of deprecated `run_all_when_everything_filtered`. Also:
- Use non-reserved words for file format and method name so that we are not accidentally shadowing important built-ins (`:format` => `:file_format`, `:method` => `:method_name`)
- Explicitly assert any new `Node` is not a `#word?` by default after initialization
- Remove unnecessary parens from let definitions in specs
> Use `RSpec::Config`'s `filter_run_when_matching`

- CHANGELOG.md
- CONTRIBUTING.md
- lib/rambling/trie/nodes/node.rb
Follow-up to #38. Also fixes typos in `CHANGELOG.md` and `CONTRIBUTING.md`.
> Use `@return [self]` in `Node#terminal!` rubydoc

- tasks/ips.rb
- tasks/performance.rb
- tasks/performance/reporters/benchmark.rb
- tasks/performance/reporters/call_tree_profile.rb
- tasks/performance/reporters/flamegraph.rb
- tasks/performance/reporters/memory_profile.rb
Plus:
- More accurate `pop`/`shift`/`slice!` reporting
- Only require `benchmark/ips` when necessary
- One-liner blocks
> Update `CallTreeProfiler` to use new `RubyProf::Profiler` format

- spec/spec_helper.rb
... by using the same filter as we use for `Coveralls.wear!`
> Exclude `spec/` from `simplecov` coverage

- .codeclimate.yml
- .rubocop.yml
- lib/rambling/trie.rb
- lib/rambling/trie/comparable.rb
- lib/rambling/trie/compressible.rb
- lib/rambling/trie/compressor.rb
- lib/rambling/trie/configuration/properties.rb
- lib/rambling/trie/configuration/provider_collection.rb
- lib/rambling/trie/container.rb
- lib/rambling/trie/enumerable.rb
- lib/rambling/trie/nodes/compressed.rb
- lib/rambling/trie/nodes/missing.rb
- lib/rambling/trie/nodes/node.rb
- lib/rambling/trie/readers/plain_text.rb
- lib/rambling/trie/readers/reader.rb
- lib/rambling/trie/serializers/marshal.rb
- lib/rambling/trie/serializers/yaml.rb
- lib/rambling/trie/serializers/zip.rb
- spec/support/shared_examples/a_serializer.rb
- Allow up to 5 params to be optional (same as max total params)
- Change max line length to 120.
> Add CodeClimate plugin: rubocop

- lib/rambling/trie/readers/plain_text.rb
- spec/lib/rambling/trie/container_spec.rb
- spec/lib/rambling/trie/enumerable_spec.rb
- spec/lib/rambling/trie/readers/plain_text_spec.rb
Also, ensure we have tests for both yield and enumerator paths where appropriate: `Container#each`, `Enumerable#each`.
Gotta thank the rubocop `Lint/ToEnumArguments` rule for this one!
> Fix missing params for enumerator for `Readers::PlainText#each_word`

- README.md
- lib/rambling/trie/container.rb
- spec/lib/rambling/trie/container_spec.rb
And update `README.md` to include `#push` in docs.
Gotta thank rubocop's `Style/ConcatArrayLiterals` rule for the idea here!
> Add `Container#push` to mirror `Array#push` interface

- .rubocop.disabled.yml
- .rubocop.enabled.yml
- .rubocop.yml
- Gemfile
- lib/rambling/trie/compressor.rb
- lib/rambling/trie/configuration/properties.rb
- lib/rambling/trie/serializers/file.rb
- lib/rambling/trie/serializers/zip.rb
- rambling-trie.gemspec
- spec/integration/rambling/trie_spec.rb
- spec/lib/rambling/trie/configuration/properties_spec.rb
- spec/lib/rambling/trie/configuration/provider_collection_spec.rb
- spec/lib/rambling/trie/container_spec.rb
- spec/lib/rambling/trie/readers/plain_text_spec.rb
- spec/lib/rambling/trie_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples/a_serializable_trie.rb
- spec/support/shared_examples/a_serializer.rb
- spec/support/shared_examples/a_trie_node.rb
- tasks/serialization/regenerate.rb
- Fix newer offenses; remove deprecated rules
- Explicitly disable `RSpec/Rails`, `Capybara` and `Factorybot` rules
- Enable new `Lint`, `Style` and `Rspec` rules
- Remove `add_development_dependency` and `test_files` from `Gemfile`
- Prefer `::File.write` over `::File.open`
- Remove `::` when unnecessary
- Use constants instead of strings for `instance_double`s
- Use `be_empty` instead of `match_array []`
- Prefer `FileUtils.rm_f path` instead of `File.delete if path File.exist?`
- Prefer `contain_exactly` over `match_array`
> Upgrade rubocop rules and fix new rule offenses

- lib/rambling/trie/nodes/raw.rb
- spec/lib/rambling/trie/container_spec.rb
- spec/lib/rambling/trie/nodes/raw_spec.rb
- spec/lib/rambling/trie/stringifyable_spec.rb
Turns out calling `#add` with an empty string in either `Container` or `Nodes::Raw` currently results in marking the root node as terminal, which is not the expected behavior. This PR fixes that by checking `root?` before calling `terminal!`.
> Ensure only non-root nodes are marked as terminal

- .rubocop.disabled.yml
Because the `lint` check is erroring with:
```
Error: `RSpec/Rails` cops have been extracted to the `rubocop-rspec_rails` gem.
(obsolete configuration found in .rubocop.disabled.yml, please update it)
```
And then:
```
Error: unrecognized cop or department Capybara/MatchStyle found in .rubocop.disabled.yml
unrecognized cop or department Capybara/NegationMatcher found in .rubocop.disabled.yml
unrecognized cop or department Capybara/SpecificActions found in .rubocop.disabled.yml
unrecognized cop or department Capybara/SpecificFinders found in .rubocop.disabled.yml
unrecognized cop or department Capybara/SpecificMatcher found in .rubocop.disabled.yml
unrecognized cop or department FactoryBot/ConsistentParenthesesStyle found in .rubocop.disabled.yml
unrecognized cop or department …
```
> Remove now-invalid cops from rubocop

- .codeclimate.yml
- .github/workflows/ruby.yml
- .reek.yml
- Gemfile
- lib/rambling/trie/compressor.rb
- lib/rambling/trie/configuration/properties.rb
- lib/rambling/trie/configuration/provider_collection.rb
- lib/rambling/trie/container.rb
- lib/rambling/trie/nodes/compressed.rb
- lib/rambling/trie/nodes/node.rb
- lib/rambling/trie/nodes/raw.rb
- lib/rambling/trie/serializers/zip.rb
- sig/lib/rambling/trie/compressor.rbs
- sig/lib/rambling/trie/nodes/compressed.rbs
- Add `reek` gem, exclude `tasks` and `spec` from checks
- Add `.reek.yml` with exclusions
- Add `lint-reek` GitHub action
Code smells addressed:
- Use `return unless variable` instead of `return if variable.nil?` where appropriate, since nil check is a type check
- Extract `size` variable for `chars.length - 1` in `Container#words_within_root`
- Extract `entry_name` for `entry.name` in `Serializers::Zip`
- Use longer variable names within blocks (`char` in `Container#words_within_root`; `extension`, `provider` in `ProviderCollection#reset`) or remove altogether `p` in `ProviderCollection#contains?`
Also:
- Assign `child.parent` to `self` in all of `children_tree` during `Nodes::Compressed#initialize`
- Simplify `Compressor#merge`
- Rename `Compressor#compress{,_only}_child_and_merge`
> Add reek + codeclimate plugin + lint-reek GH action

- .rubocop.yml
- lib/rambling/trie/container.rb
- lib/rambling/trie/nodes/compressed.rb
- tasks/ips.rb
See all `Lookups` in benchmark diff below be significantly faster!
```diff
-Benchmarks for rambling-trie version 2.5.0
+Benchmarks for rambling-trie version 2.5.1
==> Creation - `Rambling::Trie.create`
5 iterations -
-                                5.166490   0.132087   5.298577 (  5.333874)
+                                5.181516   0.113003   5.294519 (  5.296937)
==> Compression - `compress!`
5 iterations -
-                                3.418139   0.379451   3.797590 (  3.800981)
+                                3.407729   0.266162   3.673891 (  3.681826)
==> Serialization (raw trie) - `Rambling::Trie.load`
5 iterations -
-                                2.309660   0.070745   2.380405 (  2.381282)
+                                2.391843   0.091314   2.483157 (  2.485032)
==> …
```
> Use `Array#shift` instead of `Array#slice!` to improve performance

- lib/rambling/trie/container.rb
- tasks/ips.rb
... during `Rambling::Trie#create` because this benchmark says it is faster (captured as the `ips:each_char_shovel_vs_chars_map`):
```
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin23]
Warming up --------------------------------------
each_char and <<    63.994k i/100ms
chars map    83.503k i/100ms
Calculating -------------------------------------
each_char and <<    615.709k (± 5.7%) i/s    (1.62 μs/i) -      3.072M in   5.006314s
chars map    814.335k (± 2.8%) i/s    (1.23 μs/i) -      4.092M in   5.028563s
Comparison:
chars map:   814335.0 i/s
each_char and <<:   615708.6 i/s - 1.32x  slower
```
Result:
```diff
==> Creation - `Rambling::Trie.create`
5 iterations -
-                                5.181516   0.113003   5.294519 (  5.296937)
+ …
```
> Use `String#chars` + `Array#map` instead of `String#each_char` + `Array#<<`

- .rubocop.yml
- lib/rambling/trie.rb
- lib/rambling/trie/compressor.rb
- lib/rambling/trie/configuration.rb
- lib/rambling/trie/configuration/provider_collection.rb
- lib/rambling/trie/container.rb
- lib/rambling/trie/enumerable.rb
- lib/rambling/trie/nodes.rb
- lib/rambling/trie/nodes/compressed.rb
- lib/rambling/trie/nodes/raw.rb
- lib/rambling/trie/readers.rb
- lib/rambling/trie/serializers.rb
- spec/spec_helper.rb
- tasks/ips.rb
For performance improvements in `words_within` lookups, particularly for compressed tries.
Also:
- Use `{ }` for blocks instead of `do/end` when they are one-liners
- Use `String#<<` for `Stringifyable`
Diff only showing significant changes:
```diff
==> Creation - `Rambling::Trie.create`
5 iterations -
-                                4.855819   0.118155   4.973974 (  4.973661)
+                                4.737132   0.141721   4.878853 (  4.881739)
...
==> Lookups (compressed trie) - `partial_word?`
200000 iterations - hi                  true
-                                0.597133   0.011527   0.608660 (  0.609033)
+                                0.553478   0.011539   0.565017 (  0.565341)
200000 iterations - help                true
-                                0.947303 …
```
> Use `Array#slice(i, slice_size)` instead `Array#slice(i..j)` of for `Container#words_within`

- .github/workflows/ruby.yml
- Rakefile
Add `steep` and `reek` rake tasks, then use `bundle exec rake <lint>` everywhere
> Use rake tasks for all lint actions

- rambling-trie.gemspec
Specifically, include `sig` in `gemspec`'s `gem.files`.
> Ensure `rbs` type signatures are included with the gem on release

- scripts/benchmark/run.sh
- tasks/helpers/garbage_collection.rb
- tasks/performance/configuration.rb
This PR:
1. Adds a benchmarking script leveraging the new `Dockerfile.benchmark` added in #80 
2. Ensures all benchmarks are run with garbage collection stopped via
```ruby
::GC.start # <= trigger garbage collection
::GC.disable # disable before executing benchmark
yield
::GC.enable # enable after executing benchmark
```
so that it doesn't interfere with benchmark calculations
After #80, I've been re-running some of the benchmarks. For the last few hours, I suspected a change in #71 slowed things down in many methods. After some up tinkering, it looked to me like the main culprit is the block `do/end` => `{ }` change. However, I continued to get wildly different results, and sometimes `{ }` would be faster than `do/end`, or just as fast.
This was extremely confusing because running a …
> Disable garbage collection in benchmarks and add script to rapidly run benchmarks for any given version

- reports/2.1.1/benchmark
- reports/2.2.0/benchmark
- reports/2.2.1/benchmark
- reports/2.3.0/benchmark
- reports/2.3.1/benchmark
- reports/2.4.0/benchmark
- reports/2.5.0/benchmark
Use:
- ruby `3.3.6` for rambling-trie `2.5.0`, `2.4.0`, `2.3.1`, `2.3.0` benchmarks
- ruby `3.0.0` for rambling-trie `2.2.1`, `2.2.0` benchmarks
- ruby `2.7.8` for rambling-trie `2.1.1` benchmarks
> Add GC-free benchmark reports for versions back to `v2.1.1`

- tasks/ips.rb
So that GC doesn't interfere with results.
> Disable garbage collection during ips benchmarks

- CHANGELOG.md
- README.md
Also: 
- Add `asdf` as an option to manage ruby versions
- Use `./<path>` for links within repo
> Add type signature information to `README`
